# Generated by Django 4.2.7 on 2024-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date restored'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='category',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date restored'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date restored'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date restored'),
        ),
        migrations.AlterField(
            model_name='image',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='image',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date restored'),
        ),
        migrations.AlterField(
            model_name='like',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='like',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date restored'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date restored'),
        ),
    ]
