# Generated by Django 4.2.7 on 2024-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'image'},
        ),
        migrations.AddField(
            model_name='discount',
            name='activate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='activation date'),
        ),
        migrations.AddField(
            model_name='discount',
            name='disactivate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deactivation date'),
        ),
        migrations.AddField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False, verbose_name='like status'),
        ),
    ]
