# Generated by Django 4.2.7 on 2024-01-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_image_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, default=models.PositiveIntegerField(), editable=False, null=True),
        ),
    ]
