# Generated by Django 4.2.7 on 2024-01-20 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='activate_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='activation date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='disactivate_at',
            field=models.DateTimeField(verbose_name='deactivation date'),
        ),
    ]
