# Generated by Django 4.2.7 on 2024-01-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_discount_activate_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='main image'),
        ),
    ]
