# Generated by Django 4.2.7 on 2024-01-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_main_image_image_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='disactivate_at',
            new_name='deactivate_at',
        ),
        migrations.AlterField(
            model_name='image',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='images'),
        ),
    ]
