# Generated by Django 4.2.7 on 2024-01-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percent'), ('amount', 'Amount')], max_length=20),
        ),
    ]
