# Generated by Django 4.2.7 on 2024-01-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'discount code'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'likes'},
        ),
    ]
