# Generated by Django 4.2.7 on 2024-01-20 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_discount_activate_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.discount', verbose_name='discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('total_price', models.PositiveIntegerField(verbose_name='total price')),
                ('discounted_total_price', models.PositiveIntegerField(verbose_name='discounted total price')),
                ('is_paid', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderitem', verbose_name='items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'order',
            },
        ),
    ]
