# Generated by Django 4.2.7 on 2024-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'در حال پردازش'), ('delivered', 'ارسال شده'), ('cancelled', 'لغو شده'), ('returned', 'بازگردانده شده')], default='processing', max_length=15, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='payment status'),
        ),
    ]
