# Generated by Django 4.2.7 on 2024-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='address',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date restored'),
        ),
    ]
