# Generated by Django 4.2.7 on 2024-01-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator')], max_length=20, null=True, verbose_name='user type'),
        ),
    ]
