# Generated by Django 4.2.7 on 2024-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='{% static "images/profile.jpg}', null=True, upload_to='users_profile_pics/', verbose_name='image'),
        ),
    ]
