# Generated by Django 4.2.7 on 2024-01-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_deleted_at_alter_address_restored_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('costumer', 'Costumer'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator')], max_length=20, null=True, verbose_name='user type'),
        ),
    ]
