# Generated by Django 4.2.7 on 2024-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code'),
        ),
    ]
