# Generated by Django 4.2.7 on 2024-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/profile.jpg', upload_to='users_profile_pics/', verbose_name='image'),
        ),
    ]
