# Generated by Django 4.2.7 on 2024-01-20 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_postal_code_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='postal code'),
            preserve_default=False,
        ),
    ]
