# Generated by Django 4.2.7 on 2024-01-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_created_at_user_deleted_at_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'address'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'user'},
        ),
    ]
