# Generated by Django 4.2.7 on 2024-01-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
    ]
